<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="tracer">
    <link name="lidar">
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}" />
            </geometry>
        </visual>
        <!-- <collision>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
            </geometry>
        </collision> -->
        <xacro:cylinder_inertial_matrix m="${lidar_mass}" r="${lidar_radius}" h="${lidar_length}" />
        <transmission name="lidar2chassis_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="lidar2chassis">
                <hardwareInterface>PositionJointInterface</hardwareInterface>
            </joint>
            <actuator name="lidar2chassis_motor">
                <mechanicalReduction>1.0</mechanicalReduction>
            </actuator>
        </transmission>
    </link>
    <!-- <joint name="lidar2chassis" type="prismatic">
        <parent link="chassis"/>
        <child link="lidar"/>
        <origin xyz="0.0 0.0 ${chassis_length/2+lidar_length/2}" rpy="0.0 0.0 0.0"/>
        <axis xyz="0 0 1.0"/>
        <limit lower="0.0" upper="1.0" effort="0.1" velocity="0.1"/>
    </joint> -->
    <joint name="lidar2chassis" type="fixed">
        <parent link="chassis" />
        <child link="lidar" />
        <origin xyz="0.0 0.0 ${chassis_length/2+lidar_length/2}" rpy="0.0 0.0 0.0" />
    </joint>
    <gazebo reference="lidar">
        <sensor name="laserscan" type="ray">
            <plugin name="laserscan" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <namespace>/</namespace>
                    <remapping>~/out:=scan</remapping>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>lidar</frame_name>
            </plugin>
            <always_on>true</always_on>
            <visualize>true</visualize>
            <update_rate>5</update_rate>
            <pose>0 0 0 0 0 0</pose>
            <!-- 激光传感器配置 -->
            <ray>
                <!-- 设置扫描范围 -->
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <resolution>1.000000</resolution>
                        <min_angle>0.000000</min_angle>
                        <max_angle>6.280000</max_angle>
                    </horizontal>
                </scan>
                <!-- 设置扫描距离 -->
                <range>
                    <min>0.120000</min>
                    <max>8.0</max>
                    <resolution>0.015000</resolution>
                </range>
                <!-- 设置噪声 -->
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
            </ray>
        </sensor>
    </gazebo>
</robot>