<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="tracer">
    <xacro:macro name="sphere_func" params="sphere_name flag">
        <link name="${sphere_name}_wheel">
            <visual>
                <geometry>
                    <sphere radius="${sphere_radius}"/>
                </geometry>
                <material name="sphere_color">
                    <color rgba="0.0 1.0 0.0 0.5"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${sphere_radius}"/>
                </geometry>
            </collision>
            <xacro:sphere_inertial_matrix m="${sphere_mass}" r="${sphere_radius}"/>
        </link>
        <joint name="${sphere_name}2chassis" type="continuous">
            <parent link="chassis"/>
            <child link="${sphere_name}_wheel"/>
            <origin xyz="${flag*0.3} 0.0 ${(sphere_radius+chassis_length/2)*-1}" rpy="0.0 0.0 0.0"/>
            <axis xyz="1 1 1" />
        </joint>
        <gaezbo reference = "${sphere_name}_wheel">
            <mu1 value = "0.0"/>
            <mu2 value = "0.0"/>
            <kp value = "1000000000.0"/>
            <kd value = "1.0"/>
        </gaezbo>
    </xacro:macro>
    <xacro:sphere_func sphere_name="front" flag = "1"/>
    <xacro:sphere_func sphere_name="behind" flag = "-1"/>
</robot>