<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="tracer">
    <link name="camera">
        <visual>
            <geometry>
                <box size="${camera_size_x} ${camera_size_y} ${camera_size_z}" />
            </geometry>
            <material name="camera_color">
                <color rgba="0.0 0.0 1.0 0.5" />
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="${camera_size_x} ${camera_size_y} ${camera_size_z}" />
            </geometry>
        </collision>
        <xacro:box_inertial_matrix m="${camera_mass}" l="${camera_size_x}" w="${camera_size_y}"
            h="${camera_size_z}" />
    </link>
    <joint name="camera2chassis" type="fixed">
        <parent link="chassis" />
        <child link="camera" />
        <origin xyz="0.3 0.0 ${chassis_length/2+camera_size_z/2+lidar_length}" rpy="0.0 0.0 0.0" />
    </joint>
    <gazebo reference="camera">
        <sensor type="depth" name="camera_sensor">
            <plugin name="depth_camera" filename="libgazebo_ros_camera.so">
                <frame_name>camera</frame_name>
            </plugin>
            <always_on>true</always_on>
            <update_rate>10</update_rate>
            <camera name="camera">
                <horizontal_fov>1.5009831567</horizontal_fov>
                <image>
                    <width>800</width>
                    <height>600</height>
                    <format>R8G8B8</format>
                </image>
                <distortion>
                    <k1>0.0</k1>
                    <k2>0.0</k2>
                    <k3>0.0</k3>
                    <p1>0.0</p1>
                    <p2>0.0</p2>
                    <center>0.5 0.5</center>
                </distortion>
            </camera>
        </sensor>
    </gazebo>

</robot>