<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="tracer">
    <xacro:macro name="wheel_func" params="wheel_name flag">
        <link name="${wheel_name}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <material name="wheel_color">
                    <color rgba="1.0 1.0 1.0 1.0"/>
                </material>
                <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
            </collision>
            <xacro:cylinder_inertial_matrix m="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}"/>
        </link>
        <joint name="${wheel_name}2chassis" type="continuous">
            <parent link="chassis"/>
            <child link="${wheel_name}_wheel"/>
            <axis xyz="0 1 0"/>
            <origin xyz="0 ${wheel_dist/2*flag} ${(sphere_radius*2+chassis_length/2-wheel_radius)*-1}" rpy="0 0 0"/>
        </joint>
        <!-- <transmission name="${wheel_name}2chassis_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${wheel_name}2chassis">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="${wheel_name}2chassis_motor">
                <mechanicalReduction>1.0</mechanicalReduction>
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </actuator>
        </transmission> -->
        <gaezbo reference = "${wheel_name}_wheel">
            <mu1 value = "20.0"/>
            <mu2 value = "20.0"/>
            <kp value = "1000000000.0"/>
            <kd value = "1.0"/>
        </gaezbo>
    </xacro:macro>
    <xacro:wheel_func wheel_name="left" flag = "1"/>
    <xacro:wheel_func wheel_name="right" flag = "-1"/>
 
    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <ros>
                <namespace>/</namespace>
                <remapping>odom:=wheel_odom</remapping>
            </ros>
            <update_rate>30.0</update_rate>

            <left_joint>left2chassis</left_joint> 
            <right_joint>right2chassis</right_joint>
            <wheel_separation>${0.6+wheel_length}</wheel_separation> 
            <wheel_diameter>${wheel_radius*2}</wheel_diameter>

            <max_wheel_torque>20</max_wheel_torque>
            <max_wheel_acceleration>1.0</max_wheel_acceleration>
            <publish_odom>true</publish_odom>
            <publish_odom_tf>false</publish_odom_tf>
            <publish_wheel_tf>true</publish_wheel_tf>
            <odometry_frame>odom</odometry_frame>
            <robot_base_frame>base_link</robot_base_frame>
        </plugin>
    </gazebo>
</robot>